// Generated by `wit-bindgen` 0.58.0. DO NOT EDIT!
#ifndef __BINDINGS_COMMAND_H
#define __BINDINGS_COMMAND_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct command_string_t {
  uint8_t*ptr;
  size_t len;
} command_string_t;

// Async Helper Functions

typedef uint32_t command_subtask_status_t;
typedef uint32_t command_subtask_t;
#define COMMAND_SUBTASK_STATE(status) ((command_subtask_state_t) ((status) & 0xf))
#define COMMAND_SUBTASK_HANDLE(status) ((command_subtask_t) ((status) >> 4))

typedef enum command_subtask_state {
  COMMAND_SUBTASK_STARTING,
  COMMAND_SUBTASK_STARTED,
  COMMAND_SUBTASK_RETURNED,
  COMMAND_SUBTASK_STARTED_CANCELLED,
  COMMAND_SUBTASK_RETURNED_CANCELLED,
} command_subtask_state_t;

command_subtask_status_t command_subtask_cancel(command_subtask_t subtask);
void command_subtask_drop(command_subtask_t subtask);

typedef uint32_t command_callback_code_t;
#define COMMAND_CALLBACK_CODE_EXIT 0
#define COMMAND_CALLBACK_CODE_YIELD 1
#define COMMAND_CALLBACK_CODE_WAIT(set) (2 | (set << 4))

typedef enum command_event_code {
  COMMAND_EVENT_NONE,
  COMMAND_EVENT_SUBTASK,
  COMMAND_EVENT_STREAM_READ,
  COMMAND_EVENT_STREAM_WRITE,
  COMMAND_EVENT_FUTURE_READ,
  COMMAND_EVENT_FUTURE_WRITE,
  COMMAND_EVENT_CANCEL,
} command_event_code_t;

typedef struct command_event {
  command_event_code_t event;
  uint32_t waitable;
  uint32_t code;
} command_event_t;

typedef uint32_t command_waitable_set_t;
command_waitable_set_t command_waitable_set_new(void);
void command_waitable_join(uint32_t waitable, command_waitable_set_t set);
void command_waitable_set_drop(command_waitable_set_t set);
void command_waitable_set_wait(command_waitable_set_t set, command_event_t *event);
void command_waitable_set_poll(command_waitable_set_t set, command_event_t *event);

void command_task_cancel(void);

typedef uint32_t command_waitable_status_t;
#define COMMAND_WAITABLE_STATE(status) ((command_waitable_state_t) ((status) & 0xf))
#define COMMAND_WAITABLE_COUNT(status) ((uint32_t) ((status) >> 4))
#define COMMAND_WAITABLE_STATUS_BLOCKED ((command_waitable_status_t) -1)

typedef enum command_waitable_state {
  COMMAND_WAITABLE_COMPLETED,
  COMMAND_WAITABLE_DROPPED,
  COMMAND_WAITABLE_CANCELLED,
} command_waitable_state_t;

void command_backpressure_inc(void);
void command_backpressure_dec(void);
void* command_context_get_0(void);
void command_context_set_0(void* value);
void command_thread_yield(void);



typedef struct {
  command_string_t f0;
  command_string_t f1;
} command_tuple2_string_string_t;

typedef struct {
  command_tuple2_string_string_t *ptr;
  size_t len;
} command_list_tuple2_string_string_t;

typedef struct {
  command_string_t *ptr;
  size_t len;
} command_list_string_t;

typedef struct {
  bool is_some;
  command_string_t val;
} command_option_string_t;

typedef struct {
  bool is_err;
} wasi_cli_exit_result_void_void_t;

typedef uint8_t wasi_cli_types_error_code_t;

// Input/output error
#define WASI_CLI_TYPES_ERROR_CODE_IO 0
// Invalid or incomplete multibyte or wide character
#define WASI_CLI_TYPES_ERROR_CODE_ILLEGAL_BYTE_SEQUENCE 1
// Broken pipe
#define WASI_CLI_TYPES_ERROR_CODE_PIPE 2

typedef wasi_cli_types_error_code_t wasi_cli_stdin_error_code_t;

typedef uint32_t wasi_cli_stdin_stream_u8_t;

typedef struct {
  bool is_err;
  union {
    wasi_cli_stdin_error_code_t err;
  } val;
} wasi_cli_stdin_result_void_error_code_t;

typedef uint32_t wasi_cli_stdin_future_result_void_error_code_t;

typedef struct {
  wasi_cli_stdin_stream_u8_t f0;
  wasi_cli_stdin_future_result_void_error_code_t f1;
} wasi_cli_stdin_tuple2_stream_u8_future_result_void_error_code_t;

typedef wasi_cli_types_error_code_t wasi_cli_stdout_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_cli_stdout_error_code_t err;
  } val;
} wasi_cli_stdout_result_void_error_code_t;

typedef uint32_t wasi_cli_stdout_future_result_void_error_code_t;

typedef wasi_cli_types_error_code_t wasi_cli_stderr_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_cli_stderr_error_code_t err;
  } val;
} wasi_cli_stderr_result_void_error_code_t;

typedef uint32_t wasi_cli_stderr_future_result_void_error_code_t;

typedef struct wasi_cli_terminal_input_own_terminal_input_t {
  int32_t __handle;
} wasi_cli_terminal_input_own_terminal_input_t;

typedef struct wasi_cli_terminal_input_borrow_terminal_input_t {
  int32_t __handle;
} wasi_cli_terminal_input_borrow_terminal_input_t;

typedef struct wasi_cli_terminal_output_own_terminal_output_t {
  int32_t __handle;
} wasi_cli_terminal_output_own_terminal_output_t;

typedef struct wasi_cli_terminal_output_borrow_terminal_output_t {
  int32_t __handle;
} wasi_cli_terminal_output_borrow_terminal_output_t;

typedef wasi_cli_terminal_input_own_terminal_input_t wasi_cli_terminal_stdin_own_terminal_input_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stdin_own_terminal_input_t val;
} wasi_cli_terminal_stdin_option_own_terminal_input_t;

typedef wasi_cli_terminal_output_own_terminal_output_t wasi_cli_terminal_stdout_own_terminal_output_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stdout_own_terminal_output_t val;
} wasi_cli_terminal_stdout_option_own_terminal_output_t;

typedef wasi_cli_terminal_output_own_terminal_output_t wasi_cli_terminal_stderr_own_terminal_output_t;

typedef struct {
  bool is_some;
  wasi_cli_terminal_stderr_own_terminal_output_t val;
} wasi_cli_terminal_stderr_option_own_terminal_output_t;

typedef uint64_t wasi_clocks_types_duration_t;

typedef wasi_clocks_types_duration_t wasi_clocks_monotonic_clock_duration_t;

typedef uint64_t wasi_clocks_monotonic_clock_mark_t;

typedef wasi_clocks_types_duration_t wasi_clocks_system_clock_duration_t;

typedef struct wasi_clocks_system_clock_instant_t {
  int64_t   seconds;
  uint32_t   nanoseconds;
} wasi_clocks_system_clock_instant_t;

typedef wasi_clocks_system_clock_instant_t wasi_filesystem_types_instant_t;

typedef uint64_t wasi_filesystem_types_filesize_t;

typedef struct wasi_filesystem_types_descriptor_type_t {
  uint8_t tag;
  union {
    command_option_string_t     other;
  } val;
} wasi_filesystem_types_descriptor_type_t;

#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_BLOCK_DEVICE 0
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_CHARACTER_DEVICE 1
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_DIRECTORY 2
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_FIFO 3
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_SYMBOLIC_LINK 4
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_REGULAR_FILE 5
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_SOCKET 6
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_TYPE_OTHER 7

typedef uint8_t wasi_filesystem_types_descriptor_flags_t;

#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_READ (1 << 0)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_WRITE (1 << 1)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_FILE_INTEGRITY_SYNC (1 << 2)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_DATA_INTEGRITY_SYNC (1 << 3)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_REQUESTED_WRITE_SYNC (1 << 4)
#define WASI_FILESYSTEM_TYPES_DESCRIPTOR_FLAGS_MUTATE_DIRECTORY (1 << 5)

typedef uint8_t wasi_filesystem_types_path_flags_t;

#define WASI_FILESYSTEM_TYPES_PATH_FLAGS_SYMLINK_FOLLOW (1 << 0)

typedef uint8_t wasi_filesystem_types_open_flags_t;

#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_CREATE (1 << 0)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_DIRECTORY (1 << 1)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_EXCLUSIVE (1 << 2)
#define WASI_FILESYSTEM_TYPES_OPEN_FLAGS_TRUNCATE (1 << 3)

typedef uint64_t wasi_filesystem_types_link_count_t;

typedef struct {
  bool is_some;
  wasi_filesystem_types_instant_t val;
} wasi_filesystem_types_option_instant_t;

typedef struct wasi_filesystem_types_descriptor_stat_t {
  wasi_filesystem_types_descriptor_type_t   type;
  wasi_filesystem_types_link_count_t   link_count;
  wasi_filesystem_types_filesize_t   size;
  wasi_filesystem_types_option_instant_t   data_access_timestamp;
  wasi_filesystem_types_option_instant_t   data_modification_timestamp;
  wasi_filesystem_types_option_instant_t   status_change_timestamp;
} wasi_filesystem_types_descriptor_stat_t;

typedef struct wasi_filesystem_types_new_timestamp_t {
  uint8_t tag;
  union {
    wasi_filesystem_types_instant_t     timestamp;
  } val;
} wasi_filesystem_types_new_timestamp_t;

#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_NO_CHANGE 0
#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_NOW 1
#define WASI_FILESYSTEM_TYPES_NEW_TIMESTAMP_TIMESTAMP 2

typedef struct wasi_filesystem_types_directory_entry_t {
  wasi_filesystem_types_descriptor_type_t   type;
  command_string_t   name;
} wasi_filesystem_types_directory_entry_t;

typedef struct wasi_filesystem_types_error_code_t {
  uint8_t tag;
  union {
    command_option_string_t     other;
  } val;
} wasi_filesystem_types_error_code_t;

#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ACCESS 0
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ALREADY 1
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_BAD_DESCRIPTOR 2
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_BUSY 3
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_DEADLOCK 4
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_QUOTA 5
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_EXIST 6
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_FILE_TOO_LARGE 7
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_ILLEGAL_BYTE_SEQUENCE 8
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IN_PROGRESS 9
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INTERRUPTED 10
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INVALID 11
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IO 12
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_IS_DIRECTORY 13
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_LOOP 14
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_TOO_MANY_LINKS 15
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_MESSAGE_SIZE 16
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NAME_TOO_LONG 17
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_DEVICE 18
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_ENTRY 19
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_LOCK 20
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INSUFFICIENT_MEMORY 21
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INSUFFICIENT_SPACE 22
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_DIRECTORY 23
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_EMPTY 24
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_RECOVERABLE 25
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_UNSUPPORTED 26
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_TTY 27
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NO_SUCH_DEVICE 28
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_OVERFLOW 29
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_NOT_PERMITTED 30
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_PIPE 31
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_READ_ONLY 32
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_INVALID_SEEK 33
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_TEXT_FILE_BUSY 34
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_CROSS_DEVICE 35
#define WASI_FILESYSTEM_TYPES_ERROR_CODE_OTHER 36

typedef uint8_t wasi_filesystem_types_advice_t;

#define WASI_FILESYSTEM_TYPES_ADVICE_NORMAL 0
#define WASI_FILESYSTEM_TYPES_ADVICE_SEQUENTIAL 1
#define WASI_FILESYSTEM_TYPES_ADVICE_RANDOM 2
#define WASI_FILESYSTEM_TYPES_ADVICE_WILL_NEED 3
#define WASI_FILESYSTEM_TYPES_ADVICE_DONT_NEED 4
#define WASI_FILESYSTEM_TYPES_ADVICE_NO_REUSE 5

typedef struct wasi_filesystem_types_metadata_hash_value_t {
  uint64_t   lower;
  uint64_t   upper;
} wasi_filesystem_types_metadata_hash_value_t;

typedef struct wasi_filesystem_types_own_descriptor_t {
  int32_t __handle;
} wasi_filesystem_types_own_descriptor_t;

typedef struct wasi_filesystem_types_borrow_descriptor_t {
  int32_t __handle;
} wasi_filesystem_types_borrow_descriptor_t;

typedef uint32_t wasi_filesystem_types_stream_u8_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_void_error_code_t;

typedef uint32_t wasi_filesystem_types_future_result_void_error_code_t;

typedef struct {
  wasi_filesystem_types_stream_u8_t f0;
  wasi_filesystem_types_future_result_void_error_code_t f1;
} wasi_filesystem_types_tuple2_stream_u8_future_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_flags_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_flags_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_type_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_type_error_code_t;

typedef uint32_t wasi_filesystem_types_stream_directory_entry_t;

typedef struct {
  wasi_filesystem_types_stream_directory_entry_t f0;
  wasi_filesystem_types_future_result_void_error_code_t f1;
} wasi_filesystem_types_tuple2_stream_directory_entry_future_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_descriptor_stat_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_descriptor_stat_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_own_descriptor_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_own_descriptor_error_code_t;

typedef struct {
  bool is_err;
  union {
    command_string_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_string_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_filesystem_types_metadata_hash_value_t ok;
    wasi_filesystem_types_error_code_t err;
  } val;
} wasi_filesystem_types_result_metadata_hash_value_error_code_t;
typedef struct wasi_filesystem_types_method_descriptor_set_times_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  wasi_filesystem_types_new_timestamp_t data_access_timestamp;
  wasi_filesystem_types_new_timestamp_t data_modification_timestamp;
} wasi_filesystem_types_method_descriptor_set_times_args_t;
typedef struct wasi_filesystem_types_method_descriptor_set_times_at_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  wasi_filesystem_types_path_flags_t path_flags;
  command_string_t path;
  wasi_filesystem_types_new_timestamp_t data_access_timestamp;
  wasi_filesystem_types_new_timestamp_t data_modification_timestamp;
} wasi_filesystem_types_method_descriptor_set_times_at_args_t;
typedef struct wasi_filesystem_types_method_descriptor_link_at_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  wasi_filesystem_types_path_flags_t old_path_flags;
  command_string_t old_path;
  wasi_filesystem_types_borrow_descriptor_t new_descriptor;
  command_string_t new_path;
} wasi_filesystem_types_method_descriptor_link_at_args_t;
typedef struct wasi_filesystem_types_method_descriptor_open_at_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  wasi_filesystem_types_path_flags_t path_flags;
  command_string_t path;
  wasi_filesystem_types_open_flags_t open_flags;
  wasi_filesystem_types_descriptor_flags_t flags;
} wasi_filesystem_types_method_descriptor_open_at_args_t;
typedef struct wasi_filesystem_types_method_descriptor_rename_at_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  command_string_t old_path;
  wasi_filesystem_types_borrow_descriptor_t new_descriptor;
  command_string_t new_path;
} wasi_filesystem_types_method_descriptor_rename_at_args_t;
typedef struct wasi_filesystem_types_method_descriptor_symlink_at_args {
  wasi_filesystem_types_borrow_descriptor_t self;
  command_string_t old_path;
  command_string_t new_path;
} wasi_filesystem_types_method_descriptor_symlink_at_args_t;

typedef wasi_filesystem_types_own_descriptor_t wasi_filesystem_preopens_own_descriptor_t;

typedef struct {
  wasi_filesystem_preopens_own_descriptor_t f0;
  command_string_t f1;
} wasi_filesystem_preopens_tuple2_own_descriptor_string_t;

typedef struct {
  wasi_filesystem_preopens_tuple2_own_descriptor_string_t *ptr;
  size_t len;
} wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t;

typedef wasi_clocks_types_duration_t wasi_sockets_types_duration_t;

typedef struct wasi_sockets_types_error_code_t {
  uint8_t tag;
  union {
    command_option_string_t     other;
  } val;
} wasi_sockets_types_error_code_t;

#define WASI_SOCKETS_TYPES_ERROR_CODE_ACCESS_DENIED 0
#define WASI_SOCKETS_TYPES_ERROR_CODE_NOT_SUPPORTED 1
#define WASI_SOCKETS_TYPES_ERROR_CODE_INVALID_ARGUMENT 2
#define WASI_SOCKETS_TYPES_ERROR_CODE_OUT_OF_MEMORY 3
#define WASI_SOCKETS_TYPES_ERROR_CODE_TIMEOUT 4
#define WASI_SOCKETS_TYPES_ERROR_CODE_INVALID_STATE 5
#define WASI_SOCKETS_TYPES_ERROR_CODE_ADDRESS_NOT_BINDABLE 6
#define WASI_SOCKETS_TYPES_ERROR_CODE_ADDRESS_IN_USE 7
#define WASI_SOCKETS_TYPES_ERROR_CODE_REMOTE_UNREACHABLE 8
#define WASI_SOCKETS_TYPES_ERROR_CODE_CONNECTION_REFUSED 9
#define WASI_SOCKETS_TYPES_ERROR_CODE_CONNECTION_BROKEN 10
#define WASI_SOCKETS_TYPES_ERROR_CODE_CONNECTION_RESET 11
#define WASI_SOCKETS_TYPES_ERROR_CODE_CONNECTION_ABORTED 12
#define WASI_SOCKETS_TYPES_ERROR_CODE_DATAGRAM_TOO_LARGE 13
#define WASI_SOCKETS_TYPES_ERROR_CODE_OTHER 14

typedef uint8_t wasi_sockets_types_ip_address_family_t;

#define WASI_SOCKETS_TYPES_IP_ADDRESS_FAMILY_IPV4 0
#define WASI_SOCKETS_TYPES_IP_ADDRESS_FAMILY_IPV6 1

typedef struct wasi_sockets_types_ipv4_address_t {
  uint8_t   f0;
  uint8_t   f1;
  uint8_t   f2;
  uint8_t   f3;
} wasi_sockets_types_ipv4_address_t;

typedef struct wasi_sockets_types_ipv6_address_t {
  uint16_t   f0;
  uint16_t   f1;
  uint16_t   f2;
  uint16_t   f3;
  uint16_t   f4;
  uint16_t   f5;
  uint16_t   f6;
  uint16_t   f7;
} wasi_sockets_types_ipv6_address_t;

typedef struct wasi_sockets_types_ip_address_t {
  uint8_t tag;
  union {
    wasi_sockets_types_ipv4_address_t     ipv4;
    wasi_sockets_types_ipv6_address_t     ipv6;
  } val;
} wasi_sockets_types_ip_address_t;

#define WASI_SOCKETS_TYPES_IP_ADDRESS_IPV4 0
#define WASI_SOCKETS_TYPES_IP_ADDRESS_IPV6 1

typedef struct wasi_sockets_types_ipv4_socket_address_t {
  uint16_t   port;
  wasi_sockets_types_ipv4_address_t   address;
} wasi_sockets_types_ipv4_socket_address_t;

typedef struct wasi_sockets_types_ipv6_socket_address_t {
  uint16_t   port;
  uint32_t   flow_info;
  wasi_sockets_types_ipv6_address_t   address;
  uint32_t   scope_id;
} wasi_sockets_types_ipv6_socket_address_t;

typedef struct wasi_sockets_types_ip_socket_address_t {
  uint8_t tag;
  union {
    wasi_sockets_types_ipv4_socket_address_t     ipv4;
    wasi_sockets_types_ipv6_socket_address_t     ipv6;
  } val;
} wasi_sockets_types_ip_socket_address_t;

#define WASI_SOCKETS_TYPES_IP_SOCKET_ADDRESS_IPV4 0
#define WASI_SOCKETS_TYPES_IP_SOCKET_ADDRESS_IPV6 1

typedef struct wasi_sockets_types_own_tcp_socket_t {
  int32_t __handle;
} wasi_sockets_types_own_tcp_socket_t;

typedef struct wasi_sockets_types_borrow_tcp_socket_t {
  int32_t __handle;
} wasi_sockets_types_borrow_tcp_socket_t;

typedef struct wasi_sockets_types_own_udp_socket_t {
  int32_t __handle;
} wasi_sockets_types_own_udp_socket_t;

typedef struct wasi_sockets_types_borrow_udp_socket_t {
  int32_t __handle;
} wasi_sockets_types_borrow_udp_socket_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_own_tcp_socket_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_own_tcp_socket_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_void_error_code_t;

typedef uint32_t wasi_sockets_types_stream_own_tcp_socket_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_stream_own_tcp_socket_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_stream_own_tcp_socket_error_code_t;

typedef uint32_t wasi_sockets_types_stream_u8_t;

typedef uint32_t wasi_sockets_types_future_result_void_error_code_t;

typedef struct {
  wasi_sockets_types_stream_u8_t f0;
  wasi_sockets_types_future_result_void_error_code_t f1;
} wasi_sockets_types_tuple2_stream_u8_future_result_void_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_ip_socket_address_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_ip_socket_address_error_code_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_bool_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_duration_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_duration_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_u32_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint8_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_u8_error_code_t;

typedef struct {
  bool is_err;
  union {
    uint64_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_u64_error_code_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_own_udp_socket_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_own_udp_socket_error_code_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} command_list_u8_t;

typedef struct {
  bool is_some;
  wasi_sockets_types_ip_socket_address_t val;
} wasi_sockets_types_option_ip_socket_address_t;

typedef struct {
  command_list_u8_t f0;
  wasi_sockets_types_ip_socket_address_t f1;
} wasi_sockets_types_tuple2_list_u8_ip_socket_address_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_types_tuple2_list_u8_ip_socket_address_t ok;
    wasi_sockets_types_error_code_t err;
  } val;
} wasi_sockets_types_result_tuple2_list_u8_ip_socket_address_error_code_t;
typedef struct wasi_sockets_types_method_tcp_socket_connect_args {
  wasi_sockets_types_borrow_tcp_socket_t self;
  wasi_sockets_types_ip_socket_address_t remote_address;
} wasi_sockets_types_method_tcp_socket_connect_args_t;
typedef struct wasi_sockets_types_method_udp_socket_send_args {
  wasi_sockets_types_borrow_udp_socket_t self;
  command_list_u8_t data;
  wasi_sockets_types_option_ip_socket_address_t remote_address;
} wasi_sockets_types_method_udp_socket_send_args_t;

typedef wasi_sockets_types_ip_address_t wasi_sockets_ip_name_lookup_ip_address_t;

typedef struct wasi_sockets_ip_name_lookup_error_code_t {
  uint8_t tag;
  union {
    command_option_string_t     other;
  } val;
} wasi_sockets_ip_name_lookup_error_code_t;

#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_ACCESS_DENIED 0
#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_INVALID_ARGUMENT 1
#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_NAME_UNRESOLVABLE 2
#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_TEMPORARY_RESOLVER_FAILURE 3
#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_PERMANENT_RESOLVER_FAILURE 4
#define WASI_SOCKETS_IP_NAME_LOOKUP_ERROR_CODE_OTHER 5

typedef struct {
  wasi_sockets_ip_name_lookup_ip_address_t *ptr;
  size_t len;
} wasi_sockets_ip_name_lookup_list_ip_address_t;

typedef struct {
  bool is_err;
  union {
    wasi_sockets_ip_name_lookup_list_ip_address_t ok;
    wasi_sockets_ip_name_lookup_error_code_t err;
  } val;
} wasi_sockets_ip_name_lookup_result_list_ip_address_error_code_t;

typedef struct {
  uint64_t f0;
  uint64_t f1;
} command_tuple2_u64_u64_t;

typedef struct {
  bool is_err;
} exports_wasi_cli_run_result_void_void_t;

// Imported Functions from `wasi:cli/environment@0.3.0`
// Get the POSIX-style environment variables.
// 
// Each environment variable is provided as a pair of string variable names
// and string value.
// 
// Morally, these are a value import, but until value imports are available
// in the component model, this import function should return the same
// values each time it is called.
extern void wasi_cli_environment_get_environment(command_list_tuple2_string_string_t *ret);
// Get the POSIX-style arguments to the program.
extern void wasi_cli_environment_get_arguments(command_list_string_t *ret);
// Return a path that programs should use as their initial current working
// directory, interpreting `.` as shorthand for this.
extern bool wasi_cli_environment_get_initial_cwd(command_string_t *ret);

// Imported Functions from `wasi:cli/exit@0.3.0`
// Exit the current instance and any linked instances.
extern void wasi_cli_exit_exit(wasi_cli_exit_result_void_void_t *status);
// Exit the current instance and any linked instances, reporting the
// specified status code to the host.
// 
// The meaning of the code depends on the context, with 0 usually meaning
// "success", and other values indicating various types of failure.
// 
// This function does not return; the effect is analogous to a trap, but
// without the connotation that something bad has happened.
extern void wasi_cli_exit_exit_with_code(uint8_t status_code);

// Imported Functions from `wasi:cli/stdin@0.3.0`
// Return a stream for reading from stdin.
// 
// This function returns a stream which provides data read from stdin,
// and a future to signal read results.
// 
// If the stream's readable end is dropped the future will resolve to success.
// 
// If the stream's writable end is dropped the future will either resolve to
// success if stdin was closed by the writer or to an error-code if reading
// failed for some other reason.
// 
// Multiple streams may be active at the same time. The behavior of concurrent
// reads is implementation-specific.
extern void wasi_cli_stdin_read_via_stream(wasi_cli_stdin_tuple2_stream_u8_future_result_void_error_code_t *ret);

// Imported Functions from `wasi:cli/stdout@0.3.0`
// Write the given stream to stdout.
// 
// If the stream's writable end is dropped this function will either return
// success once the entire contents of the stream have been written or an
// error-code representing a failure.
// 
// Otherwise if there is an error the readable end of the stream will be
// dropped and this function will return an error-code.
extern wasi_cli_stdout_future_result_void_error_code_t wasi_cli_stdout_write_via_stream(wasi_cli_stdin_stream_u8_t data);

// Imported Functions from `wasi:cli/stderr@0.3.0`
// Write the given stream to stderr.
// 
// If the stream's writable end is dropped this function will either return
// success once the entire contents of the stream have been written or an
// error-code representing a failure.
// 
// Otherwise if there is an error the readable end of the stream will be
// dropped and this function will return an error-code.
extern wasi_cli_stderr_future_result_void_error_code_t wasi_cli_stderr_write_via_stream(wasi_cli_stdin_stream_u8_t data);

// Imported Functions from `wasi:cli/terminal-stdin@0.3.0`
// If stdin is connected to a terminal, return a `terminal-input` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stdin_get_terminal_stdin(wasi_cli_terminal_stdin_own_terminal_input_t *ret);

// Imported Functions from `wasi:cli/terminal-stdout@0.3.0`
// If stdout is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stdout_get_terminal_stdout(wasi_cli_terminal_stdout_own_terminal_output_t *ret);

// Imported Functions from `wasi:cli/terminal-stderr@0.3.0`
// If stderr is connected to a terminal, return a `terminal-output` handle
// allowing further interaction with it.
extern bool wasi_cli_terminal_stderr_get_terminal_stderr(wasi_cli_terminal_stderr_own_terminal_output_t *ret);

// Imported Functions from `wasi:clocks/monotonic-clock@0.3.0`
extern wasi_clocks_monotonic_clock_mark_t wasi_clocks_monotonic_clock_now(void);
extern wasi_clocks_monotonic_clock_duration_t wasi_clocks_monotonic_clock_get_resolution(void);
extern command_subtask_status_t wasi_clocks_monotonic_clock_wait_until(wasi_clocks_monotonic_clock_mark_t when);
extern command_subtask_status_t wasi_clocks_monotonic_clock_wait_for(wasi_clocks_monotonic_clock_duration_t how_long);

// Imported Functions from `wasi:clocks/system-clock@0.3.0`
extern void wasi_clocks_system_clock_now(wasi_clocks_system_clock_instant_t *ret);
extern wasi_clocks_system_clock_duration_t wasi_clocks_system_clock_get_resolution(void);

// Imported Functions from `wasi:filesystem/types@0.3.0`
extern void wasi_filesystem_types_method_descriptor_read_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_tuple2_stream_u8_future_result_void_error_code_t *ret);
extern wasi_filesystem_types_future_result_void_error_code_t wasi_filesystem_types_method_descriptor_write_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_stream_u8_t data, wasi_filesystem_types_filesize_t offset);
extern wasi_filesystem_types_future_result_void_error_code_t wasi_filesystem_types_method_descriptor_append_via_stream(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_stream_u8_t data);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_advise(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t offset, wasi_filesystem_types_filesize_t length, wasi_filesystem_types_advice_t advice, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_sync_data(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_get_flags(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_flags_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_get_type(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_type_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_set_size(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_filesize_t size, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_set_times(wasi_filesystem_types_method_descriptor_set_times_args_t *args, wasi_filesystem_types_result_void_error_code_t *result);
extern void wasi_filesystem_types_method_descriptor_read_directory(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_tuple2_stream_directory_entry_future_result_void_error_code_t *ret);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_sync(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_create_directory_at(wasi_filesystem_types_borrow_descriptor_t self, command_string_t path, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_stat(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_descriptor_stat_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_stat_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, command_string_t path, wasi_filesystem_types_result_descriptor_stat_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_set_times_at(wasi_filesystem_types_method_descriptor_set_times_at_args_t *args, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_link_at(wasi_filesystem_types_method_descriptor_link_at_args_t *args, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_open_at(wasi_filesystem_types_method_descriptor_open_at_args_t *args, wasi_filesystem_types_result_own_descriptor_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_readlink_at(wasi_filesystem_types_borrow_descriptor_t self, command_string_t path, wasi_filesystem_types_result_string_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_remove_directory_at(wasi_filesystem_types_borrow_descriptor_t self, command_string_t path, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_rename_at(wasi_filesystem_types_method_descriptor_rename_at_args_t *args, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_symlink_at(wasi_filesystem_types_method_descriptor_symlink_at_args_t *args, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_unlink_file_at(wasi_filesystem_types_borrow_descriptor_t self, command_string_t path, wasi_filesystem_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_is_same_object(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_borrow_descriptor_t other, bool *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_metadata_hash(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_result_metadata_hash_value_error_code_t *result);
extern command_subtask_status_t wasi_filesystem_types_method_descriptor_metadata_hash_at(wasi_filesystem_types_borrow_descriptor_t self, wasi_filesystem_types_path_flags_t path_flags, command_string_t path, wasi_filesystem_types_result_metadata_hash_value_error_code_t *result);

// Imported Functions from `wasi:filesystem/preopens@0.3.0`
extern void wasi_filesystem_preopens_get_directories(wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t *ret);

// Imported Functions from `wasi:sockets/types@0.3.0`
extern bool wasi_sockets_types_static_tcp_socket_create(wasi_sockets_types_ip_address_family_t address_family, wasi_sockets_types_own_tcp_socket_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_bind(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_ip_socket_address_t *local_address, wasi_sockets_types_error_code_t *err);
extern command_subtask_status_t wasi_sockets_types_method_tcp_socket_connect(wasi_sockets_types_method_tcp_socket_connect_args_t *args, wasi_sockets_types_result_void_error_code_t *result);
extern bool wasi_sockets_types_method_tcp_socket_listen(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_stream_own_tcp_socket_t *ret, wasi_sockets_types_error_code_t *err);
extern wasi_sockets_types_future_result_void_error_code_t wasi_sockets_types_method_tcp_socket_send(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_stream_u8_t data);
extern void wasi_sockets_types_method_tcp_socket_receive(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_tuple2_stream_u8_future_result_void_error_code_t *ret);
extern bool wasi_sockets_types_method_tcp_socket_get_local_address(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_ip_socket_address_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_remote_address(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_ip_socket_address_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_is_listening(wasi_sockets_types_borrow_tcp_socket_t self);
extern wasi_sockets_types_ip_address_family_t wasi_sockets_types_method_tcp_socket_get_address_family(wasi_sockets_types_borrow_tcp_socket_t self);
extern bool wasi_sockets_types_method_tcp_socket_set_listen_backlog_size(wasi_sockets_types_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_keep_alive_enabled(wasi_sockets_types_borrow_tcp_socket_t self, bool *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_keep_alive_enabled(wasi_sockets_types_borrow_tcp_socket_t self, bool value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_keep_alive_idle_time(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_duration_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_keep_alive_idle_time(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_duration_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_keep_alive_interval(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_duration_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_keep_alive_interval(wasi_sockets_types_borrow_tcp_socket_t self, wasi_sockets_types_duration_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_keep_alive_count(wasi_sockets_types_borrow_tcp_socket_t self, uint32_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_keep_alive_count(wasi_sockets_types_borrow_tcp_socket_t self, uint32_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_hop_limit(wasi_sockets_types_borrow_tcp_socket_t self, uint8_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_hop_limit(wasi_sockets_types_borrow_tcp_socket_t self, uint8_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_receive_buffer_size(wasi_sockets_types_borrow_tcp_socket_t self, uint64_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_receive_buffer_size(wasi_sockets_types_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_get_send_buffer_size(wasi_sockets_types_borrow_tcp_socket_t self, uint64_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_tcp_socket_set_send_buffer_size(wasi_sockets_types_borrow_tcp_socket_t self, uint64_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_static_udp_socket_create(wasi_sockets_types_ip_address_family_t address_family, wasi_sockets_types_own_udp_socket_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_bind(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_ip_socket_address_t *local_address, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_connect(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_ip_socket_address_t *remote_address, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_disconnect(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_error_code_t *err);
extern command_subtask_status_t wasi_sockets_types_method_udp_socket_send(wasi_sockets_types_method_udp_socket_send_args_t *args, wasi_sockets_types_result_void_error_code_t *result);
extern command_subtask_status_t wasi_sockets_types_method_udp_socket_receive(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_result_tuple2_list_u8_ip_socket_address_error_code_t *result);
extern bool wasi_sockets_types_method_udp_socket_get_local_address(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_ip_socket_address_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_get_remote_address(wasi_sockets_types_borrow_udp_socket_t self, wasi_sockets_types_ip_socket_address_t *ret, wasi_sockets_types_error_code_t *err);
extern wasi_sockets_types_ip_address_family_t wasi_sockets_types_method_udp_socket_get_address_family(wasi_sockets_types_borrow_udp_socket_t self);
extern bool wasi_sockets_types_method_udp_socket_get_unicast_hop_limit(wasi_sockets_types_borrow_udp_socket_t self, uint8_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_set_unicast_hop_limit(wasi_sockets_types_borrow_udp_socket_t self, uint8_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_get_receive_buffer_size(wasi_sockets_types_borrow_udp_socket_t self, uint64_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_set_receive_buffer_size(wasi_sockets_types_borrow_udp_socket_t self, uint64_t value, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_get_send_buffer_size(wasi_sockets_types_borrow_udp_socket_t self, uint64_t *ret, wasi_sockets_types_error_code_t *err);
extern bool wasi_sockets_types_method_udp_socket_set_send_buffer_size(wasi_sockets_types_borrow_udp_socket_t self, uint64_t value, wasi_sockets_types_error_code_t *err);

// Imported Functions from `wasi:sockets/ip-name-lookup@0.3.0`
extern command_subtask_status_t wasi_sockets_ip_name_lookup_resolve_addresses(command_string_t name, wasi_sockets_ip_name_lookup_result_list_ip_address_error_code_t *result);

// Imported Functions from `wasi:random/random@0.3.0`
extern void wasi_random_random_get_random_bytes(uint64_t max_len, command_list_u8_t *ret);
extern uint64_t wasi_random_random_get_random_u64(void);

// Imported Functions from `wasi:random/insecure@0.3.0`
extern void wasi_random_insecure_get_insecure_random_bytes(uint64_t max_len, command_list_u8_t *ret);
extern uint64_t wasi_random_insecure_get_insecure_random_u64(void);

// Imported Functions from `wasi:random/insecure-seed@0.3.0`
extern void wasi_random_insecure_seed_get_insecure_seed(command_tuple2_u64_u64_t *ret);

// Exported Functions from `wasi:cli/run@0.3.0`
bool exports_wasi_cli_run_run(void);

// Helper Functions

void command_tuple2_string_string_free(command_tuple2_string_string_t *ptr);

void command_list_tuple2_string_string_free(command_list_tuple2_string_string_t *ptr);

void command_list_string_free(command_list_string_t *ptr);

void command_option_string_free(command_option_string_t *ptr);

void wasi_cli_exit_result_void_void_free(wasi_cli_exit_result_void_void_t *ptr);

void wasi_cli_stdin_result_void_error_code_free(wasi_cli_stdin_result_void_error_code_t *ptr);

typedef uint32_t wasi_cli_stdin_stream_u8_writer_t;

wasi_cli_stdin_stream_u8_t wasi_cli_stdin_stream_u8_new(wasi_cli_stdin_stream_u8_writer_t *writer);
command_waitable_status_t wasi_cli_stdin_stream_u8_read(wasi_cli_stdin_stream_u8_t reader, uint8_t *buf, size_t amt);
command_waitable_status_t wasi_cli_stdin_stream_u8_write(wasi_cli_stdin_stream_u8_writer_t writer, const uint8_t *buf, size_t amt);
command_waitable_status_t wasi_cli_stdin_stream_u8_cancel_read(wasi_cli_stdin_stream_u8_t reader);
command_waitable_status_t wasi_cli_stdin_stream_u8_cancel_write(wasi_cli_stdin_stream_u8_writer_t writer);
void wasi_cli_stdin_stream_u8_drop_readable(wasi_cli_stdin_stream_u8_t reader);
void wasi_cli_stdin_stream_u8_drop_writable(wasi_cli_stdin_stream_u8_writer_t writer);


typedef uint32_t wasi_cli_stdin_future_result_void_error_code_writer_t;

wasi_cli_stdin_future_result_void_error_code_t wasi_cli_stdin_future_result_void_error_code_new(wasi_cli_stdin_future_result_void_error_code_writer_t *writer);
command_waitable_status_t wasi_cli_stdin_future_result_void_error_code_read(wasi_cli_stdin_future_result_void_error_code_t reader, wasi_cli_stdin_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stdin_future_result_void_error_code_write(wasi_cli_stdin_future_result_void_error_code_writer_t writer, const wasi_cli_stdin_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stdin_future_result_void_error_code_cancel_read(wasi_cli_stdin_future_result_void_error_code_t reader);
command_waitable_status_t wasi_cli_stdin_future_result_void_error_code_cancel_write(wasi_cli_stdin_future_result_void_error_code_writer_t writer);
void wasi_cli_stdin_future_result_void_error_code_drop_readable(wasi_cli_stdin_future_result_void_error_code_t reader);
void wasi_cli_stdin_future_result_void_error_code_drop_writable(wasi_cli_stdin_future_result_void_error_code_writer_t writer);


void wasi_cli_stdout_result_void_error_code_free(wasi_cli_stdout_result_void_error_code_t *ptr);

typedef uint32_t wasi_cli_stdout_future_result_void_error_code_writer_t;

wasi_cli_stdout_future_result_void_error_code_t wasi_cli_stdout_future_result_void_error_code_new(wasi_cli_stdout_future_result_void_error_code_writer_t *writer);
command_waitable_status_t wasi_cli_stdout_future_result_void_error_code_read(wasi_cli_stdout_future_result_void_error_code_t reader, wasi_cli_stdout_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stdout_future_result_void_error_code_write(wasi_cli_stdout_future_result_void_error_code_writer_t writer, const wasi_cli_stdout_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stdout_future_result_void_error_code_cancel_read(wasi_cli_stdout_future_result_void_error_code_t reader);
command_waitable_status_t wasi_cli_stdout_future_result_void_error_code_cancel_write(wasi_cli_stdout_future_result_void_error_code_writer_t writer);
void wasi_cli_stdout_future_result_void_error_code_drop_readable(wasi_cli_stdout_future_result_void_error_code_t reader);
void wasi_cli_stdout_future_result_void_error_code_drop_writable(wasi_cli_stdout_future_result_void_error_code_writer_t writer);


void wasi_cli_stderr_result_void_error_code_free(wasi_cli_stderr_result_void_error_code_t *ptr);

typedef uint32_t wasi_cli_stderr_future_result_void_error_code_writer_t;

wasi_cli_stderr_future_result_void_error_code_t wasi_cli_stderr_future_result_void_error_code_new(wasi_cli_stderr_future_result_void_error_code_writer_t *writer);
command_waitable_status_t wasi_cli_stderr_future_result_void_error_code_read(wasi_cli_stderr_future_result_void_error_code_t reader, wasi_cli_stderr_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stderr_future_result_void_error_code_write(wasi_cli_stderr_future_result_void_error_code_writer_t writer, const wasi_cli_stderr_result_void_error_code_t *buf);
command_waitable_status_t wasi_cli_stderr_future_result_void_error_code_cancel_read(wasi_cli_stderr_future_result_void_error_code_t reader);
command_waitable_status_t wasi_cli_stderr_future_result_void_error_code_cancel_write(wasi_cli_stderr_future_result_void_error_code_writer_t writer);
void wasi_cli_stderr_future_result_void_error_code_drop_readable(wasi_cli_stderr_future_result_void_error_code_t reader);
void wasi_cli_stderr_future_result_void_error_code_drop_writable(wasi_cli_stderr_future_result_void_error_code_writer_t writer);


extern void wasi_cli_terminal_input_terminal_input_drop_own(wasi_cli_terminal_input_own_terminal_input_t handle);

extern void wasi_cli_terminal_input_terminal_input_drop_borrow(wasi_cli_terminal_input_borrow_terminal_input_t handle);

extern wasi_cli_terminal_input_borrow_terminal_input_t wasi_cli_terminal_input_borrow_terminal_input(wasi_cli_terminal_input_own_terminal_input_t handle);

extern void wasi_cli_terminal_output_terminal_output_drop_own(wasi_cli_terminal_output_own_terminal_output_t handle);

extern void wasi_cli_terminal_output_terminal_output_drop_borrow(wasi_cli_terminal_output_borrow_terminal_output_t handle);

extern wasi_cli_terminal_output_borrow_terminal_output_t wasi_cli_terminal_output_borrow_terminal_output(wasi_cli_terminal_output_own_terminal_output_t handle);

void wasi_cli_terminal_stdin_option_own_terminal_input_free(wasi_cli_terminal_stdin_option_own_terminal_input_t *ptr);

void wasi_cli_terminal_stdout_option_own_terminal_output_free(wasi_cli_terminal_stdout_option_own_terminal_output_t *ptr);

void wasi_cli_terminal_stderr_option_own_terminal_output_free(wasi_cli_terminal_stderr_option_own_terminal_output_t *ptr);

void wasi_filesystem_types_descriptor_type_free(wasi_filesystem_types_descriptor_type_t *ptr);

void wasi_filesystem_types_option_instant_free(wasi_filesystem_types_option_instant_t *ptr);

void wasi_filesystem_types_descriptor_stat_free(wasi_filesystem_types_descriptor_stat_t *ptr);

void wasi_filesystem_types_new_timestamp_free(wasi_filesystem_types_new_timestamp_t *ptr);

void wasi_filesystem_types_directory_entry_free(wasi_filesystem_types_directory_entry_t *ptr);

void wasi_filesystem_types_error_code_free(wasi_filesystem_types_error_code_t *ptr);

extern void wasi_filesystem_types_descriptor_drop_own(wasi_filesystem_types_own_descriptor_t handle);

extern void wasi_filesystem_types_descriptor_drop_borrow(wasi_filesystem_types_borrow_descriptor_t handle);

extern wasi_filesystem_types_borrow_descriptor_t wasi_filesystem_types_borrow_descriptor(wasi_filesystem_types_own_descriptor_t handle);

void wasi_filesystem_types_result_void_error_code_free(wasi_filesystem_types_result_void_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_flags_error_code_free(wasi_filesystem_types_result_descriptor_flags_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_type_error_code_free(wasi_filesystem_types_result_descriptor_type_error_code_t *ptr);

void wasi_filesystem_types_result_descriptor_stat_error_code_free(wasi_filesystem_types_result_descriptor_stat_error_code_t *ptr);

void wasi_filesystem_types_result_own_descriptor_error_code_free(wasi_filesystem_types_result_own_descriptor_error_code_t *ptr);

void wasi_filesystem_types_result_string_error_code_free(wasi_filesystem_types_result_string_error_code_t *ptr);

void wasi_filesystem_types_result_metadata_hash_value_error_code_free(wasi_filesystem_types_result_metadata_hash_value_error_code_t *ptr);

typedef uint32_t wasi_filesystem_types_stream_u8_writer_t;

wasi_filesystem_types_stream_u8_t wasi_filesystem_types_stream_u8_new(wasi_filesystem_types_stream_u8_writer_t *writer);
command_waitable_status_t wasi_filesystem_types_stream_u8_read(wasi_filesystem_types_stream_u8_t reader, uint8_t *buf, size_t amt);
command_waitable_status_t wasi_filesystem_types_stream_u8_write(wasi_filesystem_types_stream_u8_writer_t writer, const uint8_t *buf, size_t amt);
command_waitable_status_t wasi_filesystem_types_stream_u8_cancel_read(wasi_filesystem_types_stream_u8_t reader);
command_waitable_status_t wasi_filesystem_types_stream_u8_cancel_write(wasi_filesystem_types_stream_u8_writer_t writer);
void wasi_filesystem_types_stream_u8_drop_readable(wasi_filesystem_types_stream_u8_t reader);
void wasi_filesystem_types_stream_u8_drop_writable(wasi_filesystem_types_stream_u8_writer_t writer);


typedef uint32_t wasi_filesystem_types_future_result_void_error_code_writer_t;

wasi_filesystem_types_future_result_void_error_code_t wasi_filesystem_types_future_result_void_error_code_new(wasi_filesystem_types_future_result_void_error_code_writer_t *writer);
command_waitable_status_t wasi_filesystem_types_future_result_void_error_code_read(wasi_filesystem_types_future_result_void_error_code_t reader, wasi_filesystem_types_result_void_error_code_t *buf);
command_waitable_status_t wasi_filesystem_types_future_result_void_error_code_write(wasi_filesystem_types_future_result_void_error_code_writer_t writer, const wasi_filesystem_types_result_void_error_code_t *buf);
command_waitable_status_t wasi_filesystem_types_future_result_void_error_code_cancel_read(wasi_filesystem_types_future_result_void_error_code_t reader);
command_waitable_status_t wasi_filesystem_types_future_result_void_error_code_cancel_write(wasi_filesystem_types_future_result_void_error_code_writer_t writer);
void wasi_filesystem_types_future_result_void_error_code_drop_readable(wasi_filesystem_types_future_result_void_error_code_t reader);
void wasi_filesystem_types_future_result_void_error_code_drop_writable(wasi_filesystem_types_future_result_void_error_code_writer_t writer);


typedef uint32_t wasi_filesystem_types_stream_directory_entry_writer_t;

wasi_filesystem_types_stream_directory_entry_t wasi_filesystem_types_stream_directory_entry_new(wasi_filesystem_types_stream_directory_entry_writer_t *writer);
command_waitable_status_t wasi_filesystem_types_stream_directory_entry_read(wasi_filesystem_types_stream_directory_entry_t reader, wasi_filesystem_types_directory_entry_t *buf, size_t amt);
command_waitable_status_t wasi_filesystem_types_stream_directory_entry_write(wasi_filesystem_types_stream_directory_entry_writer_t writer, const wasi_filesystem_types_directory_entry_t *buf, size_t amt);
command_waitable_status_t wasi_filesystem_types_stream_directory_entry_cancel_read(wasi_filesystem_types_stream_directory_entry_t reader);
command_waitable_status_t wasi_filesystem_types_stream_directory_entry_cancel_write(wasi_filesystem_types_stream_directory_entry_writer_t writer);
void wasi_filesystem_types_stream_directory_entry_drop_readable(wasi_filesystem_types_stream_directory_entry_t reader);
void wasi_filesystem_types_stream_directory_entry_drop_writable(wasi_filesystem_types_stream_directory_entry_writer_t writer);


void wasi_filesystem_preopens_tuple2_own_descriptor_string_free(wasi_filesystem_preopens_tuple2_own_descriptor_string_t *ptr);

void wasi_filesystem_preopens_list_tuple2_own_descriptor_string_free(wasi_filesystem_preopens_list_tuple2_own_descriptor_string_t *ptr);

void wasi_sockets_types_error_code_free(wasi_sockets_types_error_code_t *ptr);

void wasi_sockets_types_ip_address_free(wasi_sockets_types_ip_address_t *ptr);

void wasi_sockets_types_ip_socket_address_free(wasi_sockets_types_ip_socket_address_t *ptr);

extern void wasi_sockets_types_tcp_socket_drop_own(wasi_sockets_types_own_tcp_socket_t handle);

extern void wasi_sockets_types_tcp_socket_drop_borrow(wasi_sockets_types_borrow_tcp_socket_t handle);

extern wasi_sockets_types_borrow_tcp_socket_t wasi_sockets_types_borrow_tcp_socket(wasi_sockets_types_own_tcp_socket_t handle);

extern void wasi_sockets_types_udp_socket_drop_own(wasi_sockets_types_own_udp_socket_t handle);

extern void wasi_sockets_types_udp_socket_drop_borrow(wasi_sockets_types_borrow_udp_socket_t handle);

extern wasi_sockets_types_borrow_udp_socket_t wasi_sockets_types_borrow_udp_socket(wasi_sockets_types_own_udp_socket_t handle);

void wasi_sockets_types_result_own_tcp_socket_error_code_free(wasi_sockets_types_result_own_tcp_socket_error_code_t *ptr);

void wasi_sockets_types_result_void_error_code_free(wasi_sockets_types_result_void_error_code_t *ptr);

void wasi_sockets_types_result_stream_own_tcp_socket_error_code_free(wasi_sockets_types_result_stream_own_tcp_socket_error_code_t *ptr);

void wasi_sockets_types_result_ip_socket_address_error_code_free(wasi_sockets_types_result_ip_socket_address_error_code_t *ptr);

void wasi_sockets_types_result_bool_error_code_free(wasi_sockets_types_result_bool_error_code_t *ptr);

void wasi_sockets_types_result_duration_error_code_free(wasi_sockets_types_result_duration_error_code_t *ptr);

void wasi_sockets_types_result_u32_error_code_free(wasi_sockets_types_result_u32_error_code_t *ptr);

void wasi_sockets_types_result_u8_error_code_free(wasi_sockets_types_result_u8_error_code_t *ptr);

void wasi_sockets_types_result_u64_error_code_free(wasi_sockets_types_result_u64_error_code_t *ptr);

void wasi_sockets_types_result_own_udp_socket_error_code_free(wasi_sockets_types_result_own_udp_socket_error_code_t *ptr);

void command_list_u8_free(command_list_u8_t *ptr);

void wasi_sockets_types_option_ip_socket_address_free(wasi_sockets_types_option_ip_socket_address_t *ptr);

void wasi_sockets_types_tuple2_list_u8_ip_socket_address_free(wasi_sockets_types_tuple2_list_u8_ip_socket_address_t *ptr);

void wasi_sockets_types_result_tuple2_list_u8_ip_socket_address_error_code_free(wasi_sockets_types_result_tuple2_list_u8_ip_socket_address_error_code_t *ptr);

typedef uint32_t wasi_sockets_types_stream_own_tcp_socket_writer_t;

wasi_sockets_types_stream_own_tcp_socket_t wasi_sockets_types_stream_own_tcp_socket_new(wasi_sockets_types_stream_own_tcp_socket_writer_t *writer);
command_waitable_status_t wasi_sockets_types_stream_own_tcp_socket_read(wasi_sockets_types_stream_own_tcp_socket_t reader, wasi_sockets_types_own_tcp_socket_t *buf, size_t amt);
command_waitable_status_t wasi_sockets_types_stream_own_tcp_socket_write(wasi_sockets_types_stream_own_tcp_socket_writer_t writer, const wasi_sockets_types_own_tcp_socket_t *buf, size_t amt);
command_waitable_status_t wasi_sockets_types_stream_own_tcp_socket_cancel_read(wasi_sockets_types_stream_own_tcp_socket_t reader);
command_waitable_status_t wasi_sockets_types_stream_own_tcp_socket_cancel_write(wasi_sockets_types_stream_own_tcp_socket_writer_t writer);
void wasi_sockets_types_stream_own_tcp_socket_drop_readable(wasi_sockets_types_stream_own_tcp_socket_t reader);
void wasi_sockets_types_stream_own_tcp_socket_drop_writable(wasi_sockets_types_stream_own_tcp_socket_writer_t writer);


typedef uint32_t wasi_sockets_types_stream_u8_writer_t;

wasi_sockets_types_stream_u8_t wasi_sockets_types_stream_u8_new(wasi_sockets_types_stream_u8_writer_t *writer);
command_waitable_status_t wasi_sockets_types_stream_u8_read(wasi_sockets_types_stream_u8_t reader, uint8_t *buf, size_t amt);
command_waitable_status_t wasi_sockets_types_stream_u8_write(wasi_sockets_types_stream_u8_writer_t writer, const uint8_t *buf, size_t amt);
command_waitable_status_t wasi_sockets_types_stream_u8_cancel_read(wasi_sockets_types_stream_u8_t reader);
command_waitable_status_t wasi_sockets_types_stream_u8_cancel_write(wasi_sockets_types_stream_u8_writer_t writer);
void wasi_sockets_types_stream_u8_drop_readable(wasi_sockets_types_stream_u8_t reader);
void wasi_sockets_types_stream_u8_drop_writable(wasi_sockets_types_stream_u8_writer_t writer);


typedef uint32_t wasi_sockets_types_future_result_void_error_code_writer_t;

wasi_sockets_types_future_result_void_error_code_t wasi_sockets_types_future_result_void_error_code_new(wasi_sockets_types_future_result_void_error_code_writer_t *writer);
command_waitable_status_t wasi_sockets_types_future_result_void_error_code_read(wasi_sockets_types_future_result_void_error_code_t reader, wasi_sockets_types_result_void_error_code_t *buf);
command_waitable_status_t wasi_sockets_types_future_result_void_error_code_write(wasi_sockets_types_future_result_void_error_code_writer_t writer, const wasi_sockets_types_result_void_error_code_t *buf);
command_waitable_status_t wasi_sockets_types_future_result_void_error_code_cancel_read(wasi_sockets_types_future_result_void_error_code_t reader);
command_waitable_status_t wasi_sockets_types_future_result_void_error_code_cancel_write(wasi_sockets_types_future_result_void_error_code_writer_t writer);
void wasi_sockets_types_future_result_void_error_code_drop_readable(wasi_sockets_types_future_result_void_error_code_t reader);
void wasi_sockets_types_future_result_void_error_code_drop_writable(wasi_sockets_types_future_result_void_error_code_writer_t writer);


void wasi_sockets_ip_name_lookup_ip_address_free(wasi_sockets_ip_name_lookup_ip_address_t *ptr);

void wasi_sockets_ip_name_lookup_error_code_free(wasi_sockets_ip_name_lookup_error_code_t *ptr);

void wasi_sockets_ip_name_lookup_list_ip_address_free(wasi_sockets_ip_name_lookup_list_ip_address_t *ptr);

void wasi_sockets_ip_name_lookup_result_list_ip_address_error_code_free(wasi_sockets_ip_name_lookup_result_list_ip_address_error_code_t *ptr);

void exports_wasi_cli_run_result_void_void_free(exports_wasi_cli_run_result_void_void_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void command_string_set(command_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void command_string_dup(command_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void command_string_dup_n(command_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void command_string_free(command_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
